CREATE TABLE IF NOT EXISTS Saveurs (
    id_saveur INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Aliments (
    id_aliment INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Box (
    id_box INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(30) DEFAULT NULL,
    pieces INT DEFAULT NULL,
    prix INT DEFAULT NULL,
    images VARCHAR(255) DEFAULT NULL,
    id_aliment INT,
    id_saveur INT,
    FOREIGN KEY (id_aliment) REFERENCES Aliments(id_aliment) ON DELETE CASCADE,
    FOREIGN KEY (id_saveur) REFERENCES Saveurs(id_saveur) ON DELETE CASCADE
);
